# properties
rabbitMQ:
    host: host.local
    port: 5271
    virtualhost: dev
    user: dev
    password: password
    workerWorkflowEventsQueue: worker.v1.events.workflow
    workflowEventsExchange: events.v1.workflow.exchange
    workerWorkflowCommandsQueue: worker.v1.commands.workflow.priority
    workflowCommandsExchange: commands.v1.workflow.exchange
    useSsl: true
    sslKeypassphrasePassword: keyUser
    sslTrustpassphrasePassword: ihatejordi
    sslKeypath: /certs/keycert.p12
    sslTrustpath: /certs/store